<?php
/*
 * Copyright (c) 2017-2024 Aimy Extensions, Netzum Sorglos Software GmbH
 * Copyright (c) 2014-2017 Aimy Extensions, Lingua-Systems Software GmbH
 *
 * https://www.aimy-extensions.com/
 *
 * License: GNU GPLv2, see LICENSE.txt within distribution and/or
 *          https://www.aimy-extensions.com/software-license.html
 */
 defined( '_JEXEC' ) or die(); require_once( JPATH_COMPONENT . '/helpers/config.php' ); require_once( JPATH_COMPONENT . '/helpers/compat.php' ); class AimySitemapController extends JControllerLegacy { protected $default_view = 'dashboard'; public function display( $cachable = false, $urlparams = false ) { $view = $this->input->get( 'view', $this->default_view ); $layout = $this->input->get( 'layout', 'default' ); $id = $this->input->getInt( 'id' ); if ( $view == 'urls' && $layout == 'edit' && ! $this->checkEditId( 'com_aimysitemap.edit.urls', $id ) ) { $this->setError( JText::sprintf( 'JLIB_APPLICATION_ERROR_UNHELD_ID', $id ) ); $this->setMessage( $this->getError(), 'error' ); $this->setRedirect( JRoute::_( 'index.php?option=com_aimysitemap&view=urls', false ) ); return false; } $cfg = new AimySitemapConfigHelper(); if ( ! $cfg->get( 'default_priority', 0 ) ) { JFactory::getApplication()->enqueueMessage( JText::sprintf( 'AIMY_SM_MSG_NOT_CONFIGURED', JRoute::_( 'index.php?option=com_config&' . 'view=component&' . 'component=com_aimysitemap' ) ), 'warning' ); } if ( $cfg->get( 'notify_indexnow', 'unset' ) == 'unset' ) { $cfg_url = JRoute::_( 'index.php?option=com_config&' . 'view=component&' . 'component=com_aimysitemap' ); JFactory::getApplication()->enqueueMessage( JText::sprintf( 'AIMY_SM_MSG_CHECK_OUT_INDEXNOW_XYZ', 'https://www.aimy-extensions.com/joomla/indexnow.html', $cfg_url, 'https://www.aimy-extensions.com/how-to-use-xml-sitemap-and-indexnow-together.html', $cfg_url ), 'notice' ); } $jdoc = JFactory::getDocument(); $mediaUrl = sprintf( '%s/media/com_aimysitemap/', JURI::root( true ) ); $jmajor = AimySitemapCompatHelper::getJoomlaMajorVersion(); $versionCss = sprintf( 'backend-j%d.css?r=33.1', $jmajor == 5 ? 4 : $jmajor ); $jdoc->addStylesheet( $mediaUrl . 'backend.css?r=33.1' ); $jdoc->addStylesheet( $mediaUrl . $versionCss ); $jdoc->addStylesheet( $mediaUrl . 'microalert.css?r=33.1' ); $jdoc->addScript( $mediaUrl . 'microalert.js?r=33.1' ); AimySitemapCompatHelper::loadFramework( 'jquery' ); parent::display(); return $this; } } 
